### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by bdice** [conda-forge/ovito-feedstock#8]
I'd like to try enabling macOS support for this package. I am going to try it and will offer a PR if I can make it work. Any advice or guidance you might have would be appreciated!

**Comment by jan-janssen** [comment]
@bdice I am currently struggling to build ovito with the latest QT version https://github.com/conda-forge/ovito-feedstock/pull/7 - so I am not sure if we can get it to work. When I last met Alexander, he said he plans to release version 3.0 soon, so for the moment I am waiting for 3.0.

**Comment by bdice** [comment]
@jan-janssen Thanks! I started looking into it and it seems like there are a few dependencies that would need to be resolved or replaced, which are linux-only.
- `libgcc-ng`
- `libstdcxx-ng`
- `libglu`

I am pretty new to OVITO so I'm still learning my way around the package - do you think 3.0 will fix Qt issues and/or change the dependencies?

**Comment by jan-janssen** [comment]
I hope - we have to see.

**Comment by jan-janssen** [comment]
@bdice A quick update on this issue

**Comment by jan-janssen** [comment]
I tried it once more, but was not able to compile a Mac OS X version, so I am going to close the issue for now. 
https://github.com/conda-forge/ovito-feedstock/pull/20
